- name: Déployer WordPress de façon générique
  hosts: backend_dev
  become: true
  roles:
    - role: mysql
      vars:
        db_name: wordpress
        db_user: wp_user
        db_password: wp_pass
